accounts/urls.py
from django.urls import path, re_path
from .views import (AccountHomeView, AccountEmailActivateView, UserDetailUpdateView)

app_name = "account"
urlpatterns = [
    path("", AccountHomeView.as_view(), name='home'),
    re_path(r'^details/$', UserDetailUpdateView.as_view(), name='user-update'),
    re_path(r'^email/confirm/(?P<key>[0-9A-Za-z]+)/$', AccountEmailActivateView.as_view(), name='email-activate'),
    re_path(r'^email/resend-activation/$', AccountEmailActivateView.as_view(), name='resend-activation'),
]

gcutickets/urls.py
from django.views.generic import RedirectView
from django.contrib.auth.views import LogoutView
from accounts.views import LoginView, RegisterView
from django.contrib import admin
from django.urls import path, re_path,include

urlpatterns = [
    path("", include("ticket.urls")),
    re_path(r'^accounts/$', RedirectView.as_view(url='/account')),
    path('account/', include("accounts.urls")),
    path('accounts/', include("accounts.password.urls")),
    re_path(r'^register/$', RegisterView.as_view(), name='register'),
    re_path(r'^login/$', LoginView.as_view(), name='login'),
    re_path(r'^logout/$', LogoutView.as_view(), name='logout'),
    path('admin/', admin.site.urls),
]

ticket/urls.py
from django.urls import  path,reverse_lazy
from django.views.generic import RedirectView

from .views import index,ticketDetail

app_name = 'ticket'
urlpatterns = [
    path('',index,name = 'index' ),
    path('<int:ticket_id>/',ticketDetail, name='ticketDetail'),
    path('admin', RedirectView.as_view(url=reverse_lazy('admin:index')),name='admin'),
]

templates/base/css.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

templates/base/js.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

templates/base/navbar.html
{% url 'home' as home_url %}
{% url 'contact' as contact_url %}
{% url 'products:list' as product_list_url %}
{% url 'login' as login_url %}
{% url 'logout' as logout_url %}
{% url 'register' as register_url %}

{% url 'account:home' as account_url %}
{% url 'cart:home' as cart_url %}

<nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-3">
   <div class='container'>
  <a class="navbar-brand" href="{{ home_url }}">
    <img src="//getbootstrap.com/assets/brand/bootstrap-solid.svg" width="30" height="30" class="d-inline-block align-top" alt="">
    {% if brand_name %} {{brand_name }} {% else %}CFE eCommerce {% endif %}
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item {% if request.path == home_url %}active{% endif %}">
        <a class="nav-link" href="{{ home_url }}">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item {% if request.path == contact_url %}active{% endif %}">
        <a class="nav-link" href="{{ contact_url }}">Contact</a>
      </li>
      <li class="nav-item {% if request.path == product_list_url %}active{% endif %}">
        <a class="nav-link" href="{{ product_list_url }}">Products</a>
      </li>


      {% if request.user.is_authenticated %}
       <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Account
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item {% if request.path == account_url %}active{% endif %}" href="{{ account_url }}">Home</a>
          <a class="dropdown-item" href="{{ account_url }}#billing">Billing</a>
          <a class="dropdown-item" href="{% url "account:user-product-history" %}">History</a>
          <a class='dropdown-item' href='{% url "library" %}'>Library</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="{{ logout_url }}">Logout</a>
        </div>
      </li>
      {% else %}
       <li class="nav-item {% if request.path == register_url %}active{% endif %}">
        <a class="nav-link" href="{{ register_url }}">Register</a>
      </li>
      <li class="nav-item {% if request.path == login_url %}active{% endif %}">
        <a class="nav-link" href="{{ login_url }}">Login</a>
      </li>
      {% endif %}
      <li class="nav-item {% if request.path == cart_url %}active{% endif %}">
        <a class="nav-link" href="{{ cart_url }}"><span class='navbar-cart-count'>{{ request.session.cart_items }}</span> <i class="fa fa-shopping-cart" aria-hidden="true"></i></a>
      </li>



    </ul>
    {% include 'search/snippets/search-form.html' %}
  </div>
</div>
</nav>