gcutickets/urls.py
from django.views.generic import RedirectView
from django.contrib.auth.views import LogoutView
from accounts.views import LoginView, RegisterView
from django.contrib import admin
from django.urls import path, re_path,include

urlpatterns = [
    path("", include("ticket.urls")),
    re_path(r'^accounts/$', RedirectView.as_view(url='/account')),
    path('account/', include("accounts.urls")),
    path('accounts/', include("accounts.password.urls")),
    re_path(r'^register/$', RegisterView.as_view(), name='register'),
    re_path(r'^login/$', LoginView.as_view(), name='login'),
    re_path(r'^logout/$', LogoutView.as_view(), name='logout'),
    path('admin/', admin.site.urls),
]

ticket/urls.py
from django.urls import  path,reverse_lazy
from django.views.generic import RedirectView

from .views import index,ticketDetail

app_name = 'ticket'
urlpatterns = [
    path('',index,name = 'index' ),
    path('<int:ticket_id>/',ticketDetail, name='ticketDetail'),
    path('admin', RedirectView.as_view(url=reverse_lazy('admin:index')),name='admin'),
]

ticket/models.py
from django.db import models
from accounts.models import User

PRIORITY= (
    ('LOW',"LOW"),('MEDIUM',"MEDIUM"),('HIGH',"HIGH")
)
TYPE = (("AVAILABE","AVAILABLE"),("NOT AVAILABLE","NOT AVAILABLE"),("CLOSED","CLOSED"))


class Ticket(models.Model):
    ticket_number = models.AutoField(primary_key = True)
    ticket_title = models.CharField(max_length= 250, blank= True)
    date = models.DateTimeField(auto_now_add=True)
    description = models.TextField()
    status = models.CharField(choices=TYPE, max_length=24)
    priority = models.CharField(choices= PRIORITY,max_length=12)
    creator = models.ForeignKey(User, on_delete= models.DO_NOTHING,null=True)
    assigned = models.CharField(max_length=344)

    def __str__(self):
        return str(self.ticket_number)




class Comments(models.Model):
    ticket = models.ForeignKey(Ticket,on_delete=models.CASCADE)
    timestamp = models.DateTimeField(auto_now_add=True)
    body = models.TextField()
    author = models.ForeignKey(User, on_delete= models.DO_NOTHING,null= True)

ticket/forms.py
from django import forms
from .models import Ticket,Comments

class TicketForm(forms.ModelForm):
    class Meta:
        model = Ticket
        fields = ['ticket_number', 'description', 'status', 'priority', 'assigned']

    

ticket/views.py
from django.contrib.auth.decorators import login_required
from django.http import Http404
from rest_framework import status
from rest_framework.decorators import api_view
from rest_framework.response import Response
from django.shortcuts import render,get_object_or_404,get_list_or_404
from django.views.generic.list import ListView
from .serializer import TicketSerializer
from django.contrib import messages

from ticket.models import Ticket

@login_required
def index(request):
    ticket = get_list_or_404(Ticket)
    context = {
        'ticket_list':ticket
    }
    return render(request,'ticket/index.html',context)

    
def ticketDetail(request, ticket_id):
    ticket = get_object_or_404(Ticket,pk = ticket_id)
    comments = ticket.comments_set.all()
    ticket_list = Ticket.objects.all()
    context = {
        "ticket": ticket,
        "ticket_list":ticket_list,
         "comment_list":comments
    }
    return render(request, 'ticket/index.html',context)






@api_view(['GET','POST'])
def ticket_list(request,format = None):

    if request.method == "GET":
        return Response()

@api_view(['GET','POST'])
def ticket_details(request,format = None):
        return Response()

@api_view(['GET','POST'])
def ticket_update(request,format = None):
        return Response()

@api_view(['GET','POST'])
def ticket_create(request,format = None):
        return Response()

@api_view(['GET','POST'])
def comment_create(request,format = None):
        return Response()

ticket/templates/ticket/index.html
{% extends "base.html" %} {% block content %}

<main role="main" class="container-fluid">
    <div class="row">
        <aside class="col-md-4 blog-sidebar">
            <div class="p-4 mb-3 bg-light rounded">
                <h4 class="font-italic">Tickets List</h4>
            </div>

            <div class="list-group">
                {% for ticket in ticket_list %}
                <button type="button" class="list-group-item list-group-item-action">
                    <a href="{% url 'ticket:ticketDetail' ticket.ticket_number %}">{{ ticket.ticket_title }}</a>
                </button>

                {% endfor %}

            </div>
        </aside>
        <!-- /.blog-sidebar -->
        <div class="col-md-8 blog-main">
            <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
                <h1 class="h3">Glasgow Caledonian Audio Visual Service</h1>
                <div class="btn-toolbar mb-2 mb-md-0">
                    <div class="btn-group mr-2">

                        {% if user.is_admin %}
                        <button type="button" class="btn btn-sm btn-outline-secondary">
                            <a href="{% url 'ticket:admin' %}">Create Ticket</a>
                        </button>
                        {% else %}
                        <button type="button" class="btn btn-sm btn-outline-secondary">
                            <a>Not Authorized to Create Ticket</a>
                        </button>
                        {% endif %}

                    </div>
                </div>
            </div>

            <div class="card">
                <div class="card-header">
                    <span class="badge badge-light">NO: {{ ticket.ticket_number }}</span>
                    <span class="badge badge-dark">Date: {{ ticket.date }}</span>
                    <span class="badge badge-pill badge-primary">{{ ticket.priority }}</span>
                    <button type="button" class="btn btn-sm btn-primary float-right" data-toggle="modal" data-target="#editTicket">
                        {{ ticket.status }} <span><i class="far fa-edit"></i></span>
                    </button>
                </div>
                <div class="card-body">
                    <h5 class="card-title">Requested By {{ ticket.creator }}</h5>
                    <p class="card-text">
                        {{ ticket.description }}
                    </p>
                    <blockquote class="blockquote mb-0">
                        <footer class="blockquote-footer">
                            Assigned To: <cite title="Source Title">{{ ticket.assigned }}</cite>
                        </footer>
                        <button type="button" class="btn btn-sm btn-primary float-right">
                            <i class="fas fa-comment-medical"></i>
                        </button>
                    </blockquote>
                </div>
            </div>

            <div class="card mt-3">
                <div class="card-body">
                    {% for comment in comment_list %}
                    <div class="pb-3">
                        <h5 class="card-title">Comments</h5>
                        <h6 class="card-subtitle mb-2 text-muted">{{ comment.author }} <span
                                        class="badge badge-dark">Date: {{ ticket.date }}</span></h6>

                        <p class="card-text">
                            {{ comment.body }}
                        </p>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
        <!-- /.blog-main -->
    </div>
    <!-- /.row -->


</main>

{% endblock %}